using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using UnityEngine;

    public class Icon : MonoBehaviour
    {
        public Sprite AttackIcon1;
        public Sprite AttackIcon2;
        public Sprite AttackIcon3;
        public Sprite AttackIcon4;
        public Sprite AttackIcon5;
        public Sprite AttackIcon6;
        public Sprite AttackIcon7;
        public Sprite AttackIcon8;
        public Sprite AttackIcon9;
        public Sprite AttackIcon10;
        public Sprite AttackIcon11;
        public Sprite AttackIcon12;
        public Sprite AttackIcon13;
        public Sprite AttackIcon14;
        public Sprite AttackIcon15;
        public Sprite AttackIcon16;
        public Sprite AttackIcon17;
        public Sprite AttackIcon18;
        public Sprite AttackIcon19;
        public Sprite AttackIcon20;
        public Sprite AttackIcon21;
        public Sprite AttackIcon22;
        public Sprite AttackIcon23;
        public Sprite AttackIcon24;
        public Sprite AttackIcon25;
        public Sprite AttackIcon26;
        public Sprite AttackIcon27;
        public Sprite AttackIcon28;
        public Sprite AttackIcon29;
        public Sprite AttackIcon30;
        public Sprite AttackIcon31;
        public Sprite AttackIcon32;
        public Sprite AttackIcon33;
        public Sprite AttackIcon34;
        public Sprite AttackIcon35;
        public Sprite AttackIcon36;

        public Sprite EffectIcon1;
        public Sprite EffectIcon2;
        public Sprite EffectIcon3;
        public Sprite EffectIcon4;
        public Sprite EffectIcon5;
        public Sprite EffectIcon6;
        public Sprite EffectIcon7;
        public Sprite EffectIcon8;
        public Sprite EffectIcon9;
        public Sprite EffectIcon10;
        public Sprite EffectIcon11;
        public Sprite EffectIcon12;
        public Sprite EffectIcon13;
        public Sprite EffectIcon14;
        public Sprite EffectIcon15;
        public Sprite EffectIcon16;
        public Sprite EffectIcon17;
        public Sprite EffectIcon18;
        public Sprite EffectIcon19;
        public Sprite EffectIcon20;
        public Sprite EffectIcon21;
        public Sprite EffectIcon22;
        public Sprite EffectIcon23;
        public Sprite EffectIcon24;
        public Sprite EffectIcon25;
        public Sprite EffectIcon26;
        public Sprite EffectIcon27;
        public Sprite EffectIcon28;
        public Sprite EffectIcon29;
        public Sprite EffectIcon30;
        public Sprite EffectIcon31;
        public Sprite EffectIcon32;
        public Sprite EffectIcon33;
        public Sprite EffectIcon34;
        public Sprite EffectIcon35;
        public Sprite EffectIcon36;
        public Sprite EffectIcon37;

        public Sprite PassiveIcon1;
        public Sprite PassiveIcon2;
        public Sprite PassiveIcon3;
        public Sprite PassiveIcon4;
        public Sprite PassiveIcon5;
        public Sprite PassiveIcon6;
        public Sprite PassiveIcon7;
        public Sprite PassiveIcon8;
        public Sprite PassiveIcon9;
        public Sprite PassiveIcon10;
        public Sprite PassiveIcon11;
        public Sprite PassiveIcon12;
        public Sprite PassiveIcon13;
        public Sprite PassiveIcon14;
        public Sprite PassiveIcon15;
        public Sprite PassiveIcon16;
        public Sprite PassiveIcon17;
        public Sprite PassiveIcon18;
        public Sprite PassiveIcon19;
        public Sprite PassiveIcon20;
        public Sprite PassiveIcon21;
        public Sprite PassiveIcon22;
        public Sprite PassiveIcon23;
        public Sprite PassiveIcon24;
        public Sprite PassiveIcon25;
        public Sprite PassiveIcon26;
        public Sprite PassiveIcon27;
        public Sprite PassiveIcon28;
        public Sprite PassiveIcon29;
        public Sprite PassiveIcon30;
        public Sprite PassiveIcon31;
        public Sprite PassiveIcon32;
        public Sprite PassiveIcon33;
        public Sprite PassiveIcon34;
        public Sprite PassiveIcon35;
        public Sprite PassiveIcon36;
        public Sprite PassiveIcon37;
        public Sprite PassiveIcon38;

}

